export const DEMO_USER = {
  id: 'demo-user-12345',
  email: 'demo@transpopilot.ai',
  created_at: new Date().toISOString(),
  role: 'admin' as const,
  full_name: 'Demo User',
  organization_id: 'demo-org-12345',
  phone: '+1 (555) 123-4567',
  position: 'Fleet Manager',
};

export const DEMO_ORGANIZATION = {
  id: 'demo-org-12345',
  name: 'Demo Trucking Co.',
  created_at: new Date().toISOString(),
  subscription_tier: 'enterprise' as const,
};

export const DEMO_VEHICLES = [
  {
    id: 'demo-vehicle-1',
    vehicle_number: 'TRK-001',
    make: 'Freightliner',
    model: 'Cascadia',
    year: 2022,
    vin: '1FUJGHDV8NLFX1234',
    license_plate: 'CA-TRK001',
    status: 'active' as const,
    mileage: 45234,
    fuel_type: 'Diesel',
    last_maintenance: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    next_maintenance: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    current_location: { lat: 37.7749, lng: -122.4194 },
    health_score: 92,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-vehicle-2',
    vehicle_number: 'TRK-002',
    make: 'Kenworth',
    model: 'T680',
    year: 2021,
    vin: '1XKYDP9X8MJ456789',
    license_plate: 'CA-TRK002',
    status: 'active' as const,
    mileage: 67890,
    fuel_type: 'Diesel',
    last_maintenance: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    next_maintenance: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    current_location: { lat: 34.0522, lng: -118.2437 },
    health_score: 87,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-vehicle-3',
    vehicle_number: 'TRK-003',
    make: 'Peterbilt',
    model: '579',
    year: 2023,
    vin: '1XPWD49X5FD123456',
    license_plate: 'CA-TRK003',
    status: 'active' as const,
    mileage: 23456,
    fuel_type: 'Diesel',
    last_maintenance: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    next_maintenance: new Date(Date.now() + 85 * 24 * 60 * 60 * 1000).toISOString(),
    current_location: { lat: 40.7128, lng: -74.0060 },
    health_score: 95,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-vehicle-4',
    vehicle_number: 'TRK-004',
    make: 'Volvo',
    model: 'VNL 760',
    year: 2020,
    vin: '4V4NC9EH4LN567890',
    license_plate: 'TX-TRK004',
    status: 'maintenance' as const,
    mileage: 98765,
    fuel_type: 'Diesel',
    last_maintenance: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    next_maintenance: new Date(Date.now() + 88 * 24 * 60 * 60 * 1000).toISOString(),
    current_location: { lat: 29.7604, lng: -95.3698 },
    health_score: 78,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-vehicle-5',
    vehicle_number: 'TRK-005',
    make: 'International',
    model: 'LT Series',
    year: 2022,
    vin: '3HSDJAPR9MN234567',
    license_plate: 'IL-TRK005',
    status: 'active' as const,
    mileage: 54321,
    fuel_type: 'Diesel',
    last_maintenance: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    next_maintenance: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000).toISOString(),
    current_location: { lat: 41.8781, lng: -87.6298 },
    health_score: 89,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_DRIVERS = [
  {
    id: 'demo-driver-1',
    name: 'John Smith',
    email: 'john.smith@demo.com',
    phone: '+1 (555) 234-5678',
    license_number: 'DL-12345678',
    license_expiry: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
    vehicle_id: 'demo-vehicle-1',
    hire_date: new Date(Date.now() - 730 * 24 * 60 * 60 * 1000).toISOString(),
    safety_score: 94,
    total_miles: 125000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-driver-2',
    name: 'Maria Garcia',
    email: 'maria.garcia@demo.com',
    phone: '+1 (555) 345-6789',
    license_number: 'DL-23456789',
    license_expiry: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
    vehicle_id: 'demo-vehicle-2',
    hire_date: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    safety_score: 98,
    total_miles: 89000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-driver-3',
    name: 'David Johnson',
    email: 'david.johnson@demo.com',
    phone: '+1 (555) 456-7890',
    license_number: 'DL-34567890',
    license_expiry: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
    vehicle_id: 'demo-vehicle-3',
    hire_date: new Date(Date.now() - 1095 * 24 * 60 * 60 * 1000).toISOString(),
    safety_score: 91,
    total_miles: 210000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-driver-4',
    name: 'Sarah Williams',
    email: 'sarah.williams@demo.com',
    phone: '+1 (555) 567-8901',
    license_number: 'DL-45678901',
    license_expiry: new Date(Date.now() + 300 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'inactive' as const,
    vehicle_id: null,
    hire_date: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    safety_score: 96,
    total_miles: 45000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-driver-5',
    name: 'Michael Brown',
    email: 'michael.brown@demo.com',
    phone: '+1 (555) 678-9012',
    license_number: 'DL-56789012',
    license_expiry: new Date(Date.now() + 210 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
    vehicle_id: 'demo-vehicle-5',
    hire_date: new Date(Date.now() - 545 * 24 * 60 * 60 * 1000).toISOString(),
    safety_score: 88,
    total_miles: 156000,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_GPS_TRACKING = DEMO_VEHICLES.map((vehicle, index) => ({
  id: `demo-gps-${vehicle.id}`,
  vehicle_id: vehicle.id,
  latitude: vehicle.current_location.lat,
  longitude: vehicle.current_location.lng,
  speed: Math.floor(Math.random() * 30) + 50,
  heading: Math.floor(Math.random() * 360),
  timestamp: new Date().toISOString(),
  accuracy: 5,
}));

export const DEMO_FUEL_RECORDS = [
  {
    id: 'demo-fuel-1',
    vehicle_id: 'demo-vehicle-1',
    driver_id: 'demo-driver-1',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    gallons: 120,
    cost: 456.00,
    location: 'Pilot Travel Center - Sacramento, CA',
    odometer: 45234,
    mpg: 6.8,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-fuel-2',
    vehicle_id: 'demo-vehicle-2',
    driver_id: 'demo-driver-2',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    gallons: 115,
    cost: 437.00,
    location: 'TA Travel Center - Los Angeles, CA',
    odometer: 67890,
    mpg: 7.2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-fuel-3',
    vehicle_id: 'demo-vehicle-3',
    driver_id: 'demo-driver-3',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    gallons: 125,
    cost: 475.00,
    location: "Love's Travel Stop - Phoenix, AZ",
    odometer: 23456,
    mpg: 7.5,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_ROUTES = [
  {
    id: 'demo-route-1',
    name: 'Route 1: SF to LA',
    vehicle_id: 'demo-vehicle-1',
    driver_id: 'demo-driver-1',
    start_location: 'San Francisco, CA',
    end_location: 'Los Angeles, CA',
    distance: 382,
    estimated_duration: 360,
    status: 'in_progress' as const,
    start_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    estimated_arrival: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    stops: ['Bakersfield, CA'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-route-2',
    name: 'Route 2: LA to Phoenix',
    vehicle_id: 'demo-vehicle-2',
    driver_id: 'demo-driver-2',
    start_location: 'Los Angeles, CA',
    end_location: 'Phoenix, AZ',
    distance: 373,
    estimated_duration: 330,
    status: 'completed' as const,
    start_time: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    estimated_arrival: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    stops: ['Palm Springs, CA'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-route-3',
    name: 'Route 3: Chicago to NYC',
    vehicle_id: 'demo-vehicle-3',
    driver_id: 'demo-driver-3',
    start_location: 'Chicago, IL',
    end_location: 'New York, NY',
    distance: 789,
    estimated_duration: 720,
    status: 'scheduled' as const,
    start_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    estimated_arrival: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    stops: ['Cleveland, OH', 'Pittsburgh, PA'],
    created_at: new Date().toISOString(),
  },
];

export const DEMO_SAFETY_INCIDENTS = [
  {
    id: 'demo-incident-1',
    vehicle_id: 'demo-vehicle-2',
    driver_id: 'demo-driver-2',
    type: 'Hard Braking',
    severity: 'low' as const,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Interstate 10, CA',
    description: 'Hard braking event detected at 14:32',
    resolved: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-incident-2',
    vehicle_id: 'demo-vehicle-5',
    driver_id: 'demo-driver-5',
    type: 'Speeding',
    severity: 'medium' as const,
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'I-80, NE',
    description: 'Speed exceeded limit by 8 mph',
    resolved: true,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_VEHICLE_HEALTH = DEMO_VEHICLES.map(vehicle => ({
  id: `demo-health-${vehicle.id}`,
  vehicle_id: vehicle.id,
  overall_score: vehicle.health_score,
  engine_health: Math.min(100, vehicle.health_score + Math.floor(Math.random() * 10)),
  brake_health: Math.min(100, vehicle.health_score + Math.floor(Math.random() * 5)),
  tire_health: Math.min(100, vehicle.health_score - Math.floor(Math.random() * 5)),
  transmission_health: Math.min(100, vehicle.health_score + Math.floor(Math.random() * 8)),
  last_diagnostic: new Date(Date.now() - Math.floor(Math.random() * 10) * 24 * 60 * 60 * 1000).toISOString(),
  next_service_due: vehicle.next_maintenance,
  alerts: vehicle.status === 'maintenance' ? ['Oil change required', 'Brake inspection needed'] : [],
  created_at: new Date().toISOString(),
}));

export const DEMO_DRIVER_BEHAVIOR = DEMO_DRIVERS.map(driver => ({
  id: `demo-behavior-${driver.id}`,
  driver_id: driver.id,
  safety_score: driver.safety_score,
  hard_braking_events: Math.floor(Math.random() * 5),
  rapid_acceleration_events: Math.floor(Math.random() * 3),
  speeding_events: Math.floor(Math.random() * 4),
  idle_time_hours: Math.floor(Math.random() * 20) + 10,
  night_driving_hours: Math.floor(Math.random() * 40) + 20,
  total_hours: Math.floor(Math.random() * 100) + 150,
  evaluation_period: '30 days',
  created_at: new Date().toISOString(),
}));

export const DEMO_DASHBOARD_STATS = {
  totalVehicles: DEMO_VEHICLES.length,
  activeVehicles: DEMO_VEHICLES.filter(v => v.status === 'active').length,
  totalDrivers: DEMO_DRIVERS.length,
  activeDrivers: DEMO_DRIVERS.filter(d => d.status === 'active').length,
  averageFuelEfficiency: 7.1,
  totalMiles: DEMO_DRIVERS.reduce((sum, d) => sum + d.total_miles, 0),
  safetyScore: Math.round(DEMO_DRIVERS.reduce((sum, d) => sum + d.safety_score, 0) / DEMO_DRIVERS.length),
  activeRoutes: DEMO_ROUTES.filter(r => r.status === 'in_progress').length,
  maintenanceDue: DEMO_VEHICLES.filter(v => v.status === 'maintenance').length,
  fuelCostThisMonth: DEMO_FUEL_RECORDS.reduce((sum, f) => sum + f.cost, 0),
  recentIncidents: DEMO_SAFETY_INCIDENTS.length,
};

export const isDemoMode = () => {
  return localStorage.getItem('transpopilot_demo_mode') === 'true';
};

export const enableDemoMode = () => {
  localStorage.setItem('transpopilot_demo_mode', 'true');
};

export const disableDemoMode = () => {
  localStorage.removeItem('transpopilot_demo_mode');
};

export const getDemoData = () => ({
  user: DEMO_USER,
  organization: DEMO_ORGANIZATION,
  vehicles: DEMO_VEHICLES,
  drivers: DEMO_DRIVERS,
  gpsTracking: DEMO_GPS_TRACKING,
  fuelRecords: DEMO_FUEL_RECORDS,
  routes: DEMO_ROUTES,
  safetyIncidents: DEMO_SAFETY_INCIDENTS,
  vehicleHealth: DEMO_VEHICLE_HEALTH,
  driverBehavior: DEMO_DRIVER_BEHAVIOR,
  dashboardStats: DEMO_DASHBOARD_STATS,
});
